// App UI text in English and Vietnamese.
export const S = {
  en: {
    nav: { home: 'Home', clients: 'Clients', reviews: 'Reviews', templates: 'Texts', settings: 'Settings', profile: 'Profile' },
    navLong: { home: 'Today', clients: 'Clients', reviews: 'Review replies', templates: 'Text templates', settings: 'Salon settings', profile: 'My profile' },
    backToSite: 'Back to website',
    sampleBanner: "You're looking at a sample salon. Nothing is sent until you tap “Open in Messages.”",
    startFresh: 'Start with my salon',
    savedLocal: 'Saved on this device',
    hello: (n) => `Hi ${n}!`,
    todaySub: "Here's what needs a text today.",
    thisMonth: 'This month',
    statAsked: 'Review requests sent',
    statReturned: 'Clients came back',
    statMoney: 'Money brought in',
    moneyHint: (t) => `Clients who came back × $${t} average ticket`,
    todoReview: 'Ask for a review',
    todoReviewSub: 'Visited in the last 7 days',
    todoWinback: 'Win back',
    todoWinbackSub: "Haven't been back in their usual time",
    allDone: 'All caught up. Nice work!',
    seeAll: 'See all clients',
    recent: 'Recent activity',
    noActivity: 'No activity yet. Send your first review request!',
    act: { review_request: 'Review request sent to', winback: 'Win-back text sent to', returned: 'Came back:', visit: 'Visit recorded:' },
    ask: 'Ask for review',
    winback: 'Send win-back',
    cameIn: 'Came in today',
    weeksAgo: (w) => (w <= 0 ? 'This week' : w === 1 ? '1 week ago' : `${w} weeks ago`),
    status: { review: 'Ask for review', winback: 'Win-back due', waiting: 'Texted · waiting', ok: 'On track' },
    clientsTitle: 'Clients',
    clientsSub: 'Everyone who visits your salon. Add them as they come in, or import your list.',
    addClient: 'Add client',
    import: 'Import list',
    search: 'Search by name or phone',
    filters: { all: 'All', review: 'Ask for review', winback: 'Win-back due', waiting: 'Waiting' },
    noClients: 'No clients yet. Add your first client or import a list.',
    noMatch: 'No clients match.',
    name: 'Client name',
    phone: 'Mobile phone',
    textLang: 'Text language',
    service: 'Usual service',
    services: { fill: 'Fill', pedicure: 'Pedicure', manicure: 'Manicure', other: 'Other' },
    lastVisit: 'Last visit',
    notes: 'Notes (optional)',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    editClient: 'Edit client',
    deleteConfirm: (n) => `Delete ${n}? This can't be undone.`,
    nameErr: 'Please enter a name.',
    phoneErr: 'Please check the phone number—it should have 10 digits.',
    importTitle: 'Import your client list',
    importSub: 'Paste from a spreadsheet or your booking app export. One client per line: Name, Phone, Last visit, Service.',
    importFile: 'Or choose a .csv file',
    importPreview: (n) => `${n} clients ready to import`,
    importSkip: (n) => `${n} lines skipped (missing name or phone)`,
    importBtn: (n) => `Import ${n} clients`,
    sendTitle: { review: 'Ask for a review', winback: 'Send a win-back text' },
    sendTo: (n) => `To ${n}`,
    openMessages: 'Open in Messages',
    copy: 'Copy text',
    copied: 'Copied!',
    markSent: 'Mark as sent',
    sendHint: 'Opens the Messages app on your phone with the text ready. Just tap send.',
    missingLink: { review: 'Add your Google review link in Settings so clients can tap it.', winback: 'Add your booking link in Settings so clients can book.' },
    goSettings: 'Go to Settings',
    sentToast: 'Marked as sent',
    visitToast: 'Visit recorded',
    wonToast: (n) => `${n} came back! 🎉`,
    reviewsTitle: 'Review replies',
    reviewsSub: 'Paste a new Google review. GlowBack writes a polite reply. Approve, copy, and post it on Google.',
    addReview: 'Add a review',
    reviewer: 'Reviewer name',
    stars: 'Stars',
    reviewText: 'What they wrote',
    suggested: 'Suggested reply',
    replyLang: 'Reply language',
    approveCopy: 'Approve & copy',
    openGoogle: 'Open Google reviews',
    replied: 'Replied',
    markReplied: 'Mark as replied',
    noReviews: 'No reviews yet. When a new Google review comes in, paste it here to get a reply.',
    shareTitle: 'Your review link',
    shareSub: 'Put this on your counter card, receipts and Instagram bio.',
    noLink: 'No Google review link yet.',
    templatesTitle: 'Text templates',
    templatesSub: 'The words GlowBack uses. Edit them to sound like you.',
    tplReview: 'Review request',
    tplWinback: 'Win-back text',
    vars: 'You can use:',
    preview: 'Preview',
    reset: 'Reset to default',
    resetConfirm: 'Reset all templates to the default wording?',
    settingsTitle: 'Salon settings',
    salonName: 'Salon name',
    ownerName: 'Your name',
    salonPhone: 'Salon phone',
    email: 'Email',
    city: 'City',
    googleLink: 'Google review link',
    googleHelp: 'On Google: search your salon → tap “Ask for reviews” (or “Share review form”) → copy the link.',
    bookingLink: 'Booking link',
    bookingHelp: 'Your Square, Vagaro, Fresha or Booksy booking page. Or leave empty to use your salon phone.',
    defaultLang: 'Default text language',
    timing: 'When to send win-back texts',
    weeksAfter: (s) => `Weeks after a ${s}`,
    avgTicket: 'Average ticket ($)',
    saved: 'Saved',
    data: 'Your data',
    dataSub: 'Everything is saved in this browser on this device.',
    exportData: 'Download backup',
    importData: 'Restore backup',
    loadSample: 'Load sample salon',
    eraseAll: 'Erase everything',
    eraseConfirm: 'Erase all salon data on this device? This cannot be undone.',
    restoreErr: "That file isn't a GlowBack backup.",
    setupTitle: "Let's set up your salon",
    setupSub: 'Takes about 2 minutes. You can change anything later.',
    setupSave: 'Save and open my dashboard',
    trySample: 'Just look around with a sample salon',
    required: 'Required',
    auth: {
      signInTitle: 'Welcome back',
      signInSub: 'Sign in to your GlowBack dashboard.',
      signUpTitle: 'Create your account',
      signUpSub: '14-day free trial • No credit card • Cancel anytime',
      signInTab: 'Sign in',
      signUpTab: 'Create account',
      email: 'Email',
      password: 'Password',
      passwordHint: 'At least 6 characters',
      fullName: 'Your name',
      salonName: 'Salon name',
      language: 'Preferred language',
      signInBtn: 'Sign in',
      signUpBtn: 'Create my account',
      working: 'Please wait…',
      noAccount: "Don't have an account?",
      haveAccount: 'Already have an account?',
      emailErr: 'Please enter a valid email.',
      passwordErr: 'Password must be at least 6 characters.',
      nameErr: 'Please enter your name.',
      checkEmailTitle: 'Check your email',
      checkEmail: (e) => `We sent a confirmation link to ${e}. Open it, then sign in here.`,
      backToSignIn: 'Back to sign in',
      loading: 'Loading…',
    },
    profile: {
      nav: 'Profile',
      title: 'My profile',
      sub: 'Your account details. Only you can see this.',
      account: 'Account',
      email: 'Email (used to sign in)',
      memberSince: 'Member since',
      fullName: 'Your name',
      salonName: 'Salon name',
      phone: 'Mobile phone',
      city: 'City',
      language: 'Preferred language',
      save: 'Save profile',
      saving: 'Saving…',
      saved: 'Profile saved',
      passwordTitle: 'Change password',
      newPassword: 'New password',
      confirmPassword: 'Confirm new password',
      changePassword: 'Update password',
      passwordChanged: 'Password updated',
      mismatch: "The two passwords don't match.",
      signOut: 'Sign out',
      useForSalon: 'Also use these details in my salon settings',
    },
  },
  vi: {
    nav: { home: 'Hôm nay', clients: 'Khách', reviews: 'Đánh giá', templates: 'Tin nhắn', settings: 'Cài đặt', profile: 'Hồ sơ' },
    navLong: { home: 'Hôm nay', clients: 'Khách hàng', reviews: 'Trả lời đánh giá', templates: 'Mẫu tin nhắn', settings: 'Cài đặt tiệm', profile: 'Hồ sơ của tôi' },
    backToSite: 'Về trang chủ',
    sampleBanner: 'Đây là tiệm mẫu. Không tin nào được gửi cho đến khi chị bấm “Mở trong Tin nhắn”.',
    startFresh: 'Bắt đầu với tiệm của tôi',
    savedLocal: 'Lưu trên máy này',
    hello: (n) => `Chào ${n}!`,
    todaySub: 'Đây là những khách cần nhắn tin hôm nay.',
    thisMonth: 'Tháng này',
    statAsked: 'Tin xin đánh giá đã gửi',
    statReturned: 'Khách quay lại',
    statMoney: 'Doanh thu mang về',
    moneyHint: (t) => `Khách quay lại × $${t} trung bình mỗi lần`,
    todoReview: 'Xin đánh giá',
    todoReviewSub: 'Đã ghé trong 7 ngày qua',
    todoWinback: 'Mời quay lại',
    todoWinbackSub: 'Đã lâu chưa quay lại',
    allDone: 'Xong hết rồi. Giỏi lắm!',
    seeAll: 'Xem tất cả khách',
    recent: 'Hoạt động gần đây',
    noActivity: 'Chưa có hoạt động. Gửi tin xin đánh giá đầu tiên nhé!',
    act: { review_request: 'Đã gửi tin xin đánh giá cho', winback: 'Đã gửi tin mời quay lại cho', returned: 'Đã quay lại:', visit: 'Đã ghi nhận lần ghé:' },
    ask: 'Xin đánh giá',
    winback: 'Mời quay lại',
    cameIn: 'Hôm nay có ghé',
    weeksAgo: (w) => (w <= 0 ? 'Tuần này' : `${w} tuần trước`),
    status: { review: 'Xin đánh giá', winback: 'Cần mời lại', waiting: 'Đã nhắn · chờ', ok: 'Bình thường' },
    clientsTitle: 'Khách hàng',
    clientsSub: 'Tất cả khách của tiệm. Thêm khách khi họ đến, hoặc nhập danh sách.',
    addClient: 'Thêm khách',
    import: 'Nhập danh sách',
    search: 'Tìm theo tên hoặc số điện thoại',
    filters: { all: 'Tất cả', review: 'Xin đánh giá', winback: 'Cần mời lại', waiting: 'Đang chờ' },
    noClients: 'Chưa có khách. Thêm khách đầu tiên hoặc nhập danh sách.',
    noMatch: 'Không tìm thấy khách.',
    name: 'Tên khách',
    phone: 'Số điện thoại',
    textLang: 'Ngôn ngữ tin nhắn',
    service: 'Dịch vụ thường làm',
    services: { fill: 'Fill', pedicure: 'Làm chân', manicure: 'Làm tay', other: 'Khác' },
    lastVisit: 'Lần ghé gần nhất',
    notes: 'Ghi chú (không bắt buộc)',
    save: 'Lưu',
    cancel: 'Hủy',
    delete: 'Xóa',
    edit: 'Sửa',
    editClient: 'Sửa thông tin khách',
    deleteConfirm: (n) => `Xóa ${n}? Không thể hoàn tác.`,
    nameErr: 'Vui lòng nhập tên.',
    phoneErr: 'Vui lòng kiểm tra số điện thoại—cần đủ 10 số.',
    importTitle: 'Nhập danh sách khách',
    importSub: 'Dán từ bảng tính hoặc file xuất từ app đặt lịch. Mỗi dòng một khách: Tên, Số điện thoại, Lần ghé gần nhất, Dịch vụ.',
    importFile: 'Hoặc chọn file .csv',
    importPreview: (n) => `${n} khách sẵn sàng để nhập`,
    importSkip: (n) => `Bỏ qua ${n} dòng (thiếu tên hoặc số điện thoại)`,
    importBtn: (n) => `Nhập ${n} khách`,
    sendTitle: { review: 'Xin đánh giá', winback: 'Gửi tin mời quay lại' },
    sendTo: (n) => `Gửi cho ${n}`,
    openMessages: 'Mở trong Tin nhắn',
    copy: 'Sao chép',
    copied: 'Đã sao chép!',
    markSent: 'Đánh dấu đã gửi',
    sendHint: 'Mở app Tin nhắn trên điện thoại với nội dung soạn sẵn. Chị chỉ cần bấm gửi.',
    missingLink: { review: 'Thêm link đánh giá Google trong Cài đặt để khách bấm vào.', winback: 'Thêm link đặt lịch trong Cài đặt để khách đặt lịch.' },
    goSettings: 'Đến Cài đặt',
    sentToast: 'Đã đánh dấu đã gửi',
    visitToast: 'Đã ghi nhận lần ghé',
    wonToast: (n) => `${n} đã quay lại! 🎉`,
    reviewsTitle: 'Trả lời đánh giá',
    reviewsSub: 'Dán đánh giá Google mới vào đây. GlowBack viết sẵn câu trả lời lịch sự. Duyệt, sao chép và đăng lên Google.',
    addReview: 'Thêm đánh giá',
    reviewer: 'Tên người đánh giá',
    stars: 'Số sao',
    reviewText: 'Nội dung đánh giá',
    suggested: 'Câu trả lời gợi ý',
    replyLang: 'Ngôn ngữ trả lời',
    approveCopy: 'Duyệt & sao chép',
    openGoogle: 'Mở đánh giá Google',
    replied: 'Đã trả lời',
    markReplied: 'Đánh dấu đã trả lời',
    noReviews: 'Chưa có đánh giá. Khi có đánh giá Google mới, dán vào đây để có câu trả lời.',
    shareTitle: 'Link đánh giá của tiệm',
    shareSub: 'Để link này trên thẻ ở quầy, hóa đơn và Instagram.',
    noLink: 'Chưa có link đánh giá Google.',
    templatesTitle: 'Mẫu tin nhắn',
    templatesSub: 'Nội dung GlowBack dùng để nhắn khách. Sửa lại cho giống giọng của chị.',
    tplReview: 'Tin xin đánh giá',
    tplWinback: 'Tin mời quay lại',
    vars: 'Có thể dùng:',
    preview: 'Xem trước',
    reset: 'Khôi phục mặc định',
    resetConfirm: 'Khôi phục tất cả mẫu tin nhắn về mặc định?',
    settingsTitle: 'Cài đặt tiệm',
    salonName: 'Tên tiệm',
    ownerName: 'Tên của chị',
    salonPhone: 'Số điện thoại tiệm',
    email: 'Email',
    city: 'Thành phố',
    googleLink: 'Link đánh giá Google',
    googleHelp: 'Trên Google: tìm tên tiệm → bấm “Ask for reviews” (Xin đánh giá) → sao chép link.',
    bookingLink: 'Link đặt lịch',
    bookingHelp: 'Trang đặt lịch Square, Vagaro, Fresha hoặc Booksy. Để trống sẽ dùng số điện thoại tiệm.',
    defaultLang: 'Ngôn ngữ tin nhắn mặc định',
    timing: 'Khi nào gửi tin mời quay lại',
    weeksAfter: (s) => `Số tuần sau khi ${s}`,
    avgTicket: 'Trung bình mỗi lần ($)',
    saved: 'Đã lưu',
    data: 'Dữ liệu',
    dataSub: 'Mọi thứ được lưu trong trình duyệt trên máy này.',
    exportData: 'Tải bản sao lưu',
    importData: 'Khôi phục bản sao lưu',
    loadSample: 'Dùng tiệm mẫu',
    eraseAll: 'Xóa hết dữ liệu',
    eraseConfirm: 'Xóa toàn bộ dữ liệu tiệm trên máy này? Không thể hoàn tác.',
    restoreErr: 'File này không phải bản sao lưu GlowBack.',
    setupTitle: 'Cài đặt tiệm của chị',
    setupSub: 'Mất khoảng 2 phút. Có thể sửa lại bất cứ lúc nào.',
    setupSave: 'Lưu và mở bảng điều khiển',
    trySample: 'Xem thử với tiệm mẫu',
    required: 'Bắt buộc',
    auth: {
      signInTitle: 'Chào mừng trở lại',
      signInSub: 'Đăng nhập vào bảng điều khiển GlowBack.',
      signUpTitle: 'Tạo tài khoản',
      signUpSub: 'Dùng thử 14 ngày • Không cần thẻ • Hủy bất cứ lúc nào',
      signInTab: 'Đăng nhập',
      signUpTab: 'Tạo tài khoản',
      email: 'Email',
      password: 'Mật khẩu',
      passwordHint: 'Ít nhất 6 ký tự',
      fullName: 'Tên của chị',
      salonName: 'Tên tiệm',
      language: 'Ngôn ngữ ưa thích',
      signInBtn: 'Đăng nhập',
      signUpBtn: 'Tạo tài khoản',
      working: 'Vui lòng đợi…',
      noAccount: 'Chưa có tài khoản?',
      haveAccount: 'Đã có tài khoản?',
      emailErr: 'Vui lòng nhập email hợp lệ.',
      passwordErr: 'Mật khẩu cần ít nhất 6 ký tự.',
      nameErr: 'Vui lòng nhập tên.',
      checkEmailTitle: 'Kiểm tra email',
      checkEmail: (e) => `Chúng tôi đã gửi link xác nhận đến ${e}. Mở link đó rồi đăng nhập tại đây.`,
      backToSignIn: 'Quay lại đăng nhập',
      loading: 'Đang tải…',
    },
    profile: {
      nav: 'Hồ sơ',
      title: 'Hồ sơ của tôi',
      sub: 'Thông tin tài khoản. Chỉ mình chị xem được.',
      account: 'Tài khoản',
      email: 'Email (dùng để đăng nhập)',
      memberSince: 'Thành viên từ',
      fullName: 'Tên của chị',
      salonName: 'Tên tiệm',
      phone: 'Số điện thoại',
      city: 'Thành phố',
      language: 'Ngôn ngữ ưa thích',
      save: 'Lưu hồ sơ',
      saving: 'Đang lưu…',
      saved: 'Đã lưu hồ sơ',
      passwordTitle: 'Đổi mật khẩu',
      newPassword: 'Mật khẩu mới',
      confirmPassword: 'Nhập lại mật khẩu mới',
      changePassword: 'Cập nhật mật khẩu',
      passwordChanged: 'Đã đổi mật khẩu',
      mismatch: 'Hai mật khẩu không khớp.',
      signOut: 'Đăng xuất',
      useForSalon: 'Dùng thông tin này cho cài đặt tiệm',
    },
  },
};
